# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

TOOL_NAME := xdp_prog_user
USER_TARGETS := xdp_prog_user
XDP_TARGETS := xdp_prog_kern
# TEST_FILE := tests/test-xdp-loader.sh
# MAN_PAGE := xdp-loader.8

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk


